import type { CheckResult, Issue } from '../types.js';
import { git, gitExec } from '../util.js';

// Git history analysis: AI commit patterns, churn hotspots
export function checkHistory(cwd: string): CheckResult {
  const issues: Issue[] = [];

  // Get recent commits (last 50) — use execFileSync to avoid shell pipe interpretation
  const log = gitExec(['log', '--oneline', '-50', '--format=%H|%an|%s'], cwd);
  if (!log) {
    return { name: 'history', score: 100, maxScore: 100, issues: [], summary: 'no git history to analyze' };
  }

  const commits = log.split('\n').filter(Boolean).map(line => {
    const parts = line.split('|');
    return { hash: parts[0] || '', author: parts[1] || '', message: parts.slice(2).join('|') };
  });

  // Detect AI-attributed commits
  const aiIndicators = [
    /co-authored-by:\s*(claude|cursor|copilot|codex|aider|cline|windsurf)/i,
    /generated by/i,
  ];
  const aiAuthors = /claude|cursor|copilot|codex|aider|bot/i;

  let aiCommits = 0;
  for (const c of commits) {
    if (aiIndicators.some(p => p.test(c.message))) aiCommits++;
    else if (aiAuthors.test(c.author)) aiCommits++;
  }

  // File churn: which files change most in recent history
  const churnOutput = gitExec(['log', '-50', '--name-only', '--format='], cwd);
  if (churnOutput) {
    const fileChanges = new Map<string, number>();
    for (const line of churnOutput.split('\n')) {
      if (!line.trim()) continue;
      fileChanges.set(line, (fileChanges.get(line) || 0) + 1);
    }

    // High churn files (changed >5 times in last 50 commits)
    const hotFiles = [...fileChanges.entries()]
      .filter(([, count]) => count >= 5)
      .sort((a, b) => b[1] - a[1]);

    if (hotFiles.length > 0) {
      const top = hotFiles.slice(0, 3);
      for (const [file, count] of top) {
        issues.push({
          severity: 'info',
          message: `${file} changed ${count} times in last 50 commits — high churn, consider stabilizing`,
          file,
          fixable: false,
        });
      }
    }
  }

  // Large commits (many files changed at once — common AI pattern)
  const diffStatLog = gitExec(['log', '-20', '--format=%H', '--shortstat'], cwd);
  if (diffStatLog) {
    const bigCommits = (diffStatLog.match(/(\d+) files? changed/g) || [])
      .map(m => parseInt(m))
      .filter(n => n > 20);
    if (bigCommits.length > 2) {
      issues.push({
        severity: 'warning',
        message: `${bigCommits.length} commits touched 20+ files — large AI-generated changes are harder to review`,
        fixable: false,
      });
    }
  }

  const aiPct = commits.length > 0 ? Math.round((aiCommits / commits.length) * 100) : 0;
  const infos = issues.filter(i => i.severity === 'info').length;
  const warnings = issues.filter(i => i.severity === 'warning').length;
  const score = Math.max(0, Math.min(100, 100 - warnings * 10 - infos * 2));

  return {
    name: 'history',
    score: Math.round(score),
    maxScore: 100,
    issues,
    summary: `${commits.length} recent commits${aiPct > 0 ? ` (~${aiPct}% AI-attributed)` : ''}, ${issues.length} observation${issues.length !== 1 ? 's' : ''}`,
  };
}
